apiVersion: apps/v1
kind: ReplicaSet
metadate:
  name: my-nginx-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      project: my-project
      var: 0.1
  template:
    metadata:
      name: my-nginx-pod
      labels:
        project: my-project
        var: 0.1
spec:
containers:
- name: my-nginx-container
  image: nginx
  ports:
  - containerPort: 80